Create exercise_1-3
Dmitriy-DevOps-trainee/Homework pull request #4
Opened 2021-12-13 21:20 UTC by Dmitriy-DevOps-trainee

@cakemanator

2021-12-13 21:20 UTC, Dmitriy-DevOps-trainee commented
@cakemanator

2021-12-14 08:51 UTC, Cakemanator requested changes

2021-12-14 08:51 UTC, Cakemanator commented on exercise_1-3
> +Все новые аккаунты должны обязательно менять свои пароли каждый 30 дней.
**ВСЕ** новые аккаунты должны обязательно менять свои пароли каждый 30 дней.

2021-12-14 08:51 UTC, Cakemanator commented on exercise_1-3
> +[Dima@test ~]$ chmod u=rwx,g=rwx,o=--- /home/Dima/students
У вас должна быть директория **/home/students**, где эти три пользователя могут работать совместно с файлами.

2021-12-16 06:48 UTC, Cakemanator approved these changes

2021-12-17 18:51 UTC, merged